---
pipeline:
  fetch:
    - unit_test: deploy
profiles:
  fetch:
    script: ./scripts/fetch.sh
    output: 
      - scm_artifact.tar
  unit_test:
    input: 
      - scm_artifact.tar
    script: ./scripts/unit_test.sh
  deploy:
    input: 
      - build_artifact.tar
    script: ./scripts/deploy.sh
    environment:
      DOCKER_IMAGE: predixci/canary
      DOCKER_USERNAME: predixci
      # DOCKER_PASSWORD: set in Predix CI UI
      # SOLANO_API_KEY:  set in Predix CI UI
  default:
    script: dev/null
